language: node_js
node_js:
  - "10"
sudo: false
cache:
  yarn: true
  directories:
    - "node_modules"
services:
  - mongodb
install:
  - yarn global add codecov
  - cd server
  - yarn
  - cd ../client
  - yarn
before_script:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
script:
  - yarn build
  - cd ../server
  - yarn lint
  - yarn test:coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo ${CF_DISTRIBUTION_ID}
  - /usr/bin/python -V
  - /usr/bin/python3 -V
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws s3 rm s3://sh.diogocardoso.me --recursive --region eu-west-2
before_deploy:
  - cd ../client
notifications:
  email: false
deploy:
  provider: s3
  access_key_id:
    secure: "bWsJuVX+M3amMo5OQS+rOn7FinysMkG8ftkBYJfVpHW8J2zDMvf1UAWbUU1of04aiRrXLoQ0p5Rn1NGZkFEH3uiZR2frN9wvNjAMEClrNR83AqdEqWz8iQcJLiuJaqwbGtLN3hwVkuEECxwv3OGfI6JKRfZvHS6ulGsAY7wASi5kw4n9BtaBUtPD2iX/xg+Jw9Svir9V8Uuda/lH/HKxmo8xi5S8qxYu+RbF8/dDRVSnCgUKjJny8fqVdHtcO/ezUhQ6yM7ust0AUEAci9ouQ/ym1UpYFY9Si8oMqRvFAwBT5CbD5J4XeJi//+bJmokC+lIob204S7w8fbEKCf8YpJKLSXmB8v90RKeuYlNwxv0lwIgAXIUN99GMwoeZBNxZW6a7YyBCKJWcvm280wux2U74h2fx1ILO64TSEIwxwtlKqW6Dg9KxtCy/1T12fyrjX/0okyBky4QgQeNw9qKlVYRUSX/3o0SunI6CKBXVf1Dhf9p41xA07KWaTfqvFQdo3sDdGXZE3EiObwDFPmPnfw+fodlT3MS9yGAzi/DbaNq8a7LKZLF3VePq7ilTleQ2U9hROyp5ZOVqidDLNAT6rGhKg2F9gPDG89hmJiWiF3hHi9+ehMGhb/6uF7xVPOU41/B6lVx5By+37QJq4nHi2GzFtFSjatCSGmXrE8+vs0A="
  secret_access_key:
    secure: "rgr1LdkkMtokkDo6SvPTFSqsm/tLVFnzs5OEYCP70qat6fw4DiSnGeNQhzBq3uSiwitzymir+0w1h85SYx7zPvaGkJah9pLR0z4ZQjlWy7jD7TY/ncq2UBA77By5gPeFWZz7JfbLk2cO8jRINqeHQU24QfMwIC5O1rLQBBquceA7E1XCfp70AyI0AxpvdJ3DJ2s1Kh1R2OZhEWhZ6Iskwe09uwmeELCZxpH68Hk5uq/x6EApiFf04xZTEDSZKX8EzAactYgPvEJBMsD4h4QVj0tNrxIwkwPATrjJU90O/ILfaNnjMDdOJTVsVocKEEFBAqbrFGIcjtoT/40kkeKrXZmyjrQlAccm0H6kuY6W6cd4lJ2/IEVf+yH60SBTo438iqkfioHp4gOjpEHPcIq5RFEP/oj6ZNpAHMsG3Yf7P1GtKryM2X8mbeaDTQ8Hfcf0hjVyIBMsg4Thas8G0a+JP76wQof5FCYB385G7xcDWZ+0sbWlgkVfmDEfZJ+lPub1DwAh4koCBq9HmcioP8qdUCW2KKDtzdSiEx6CjCh7t2fK7ddnHFtWNAPBJMytuWoO8gWtKnWLiPh8U3afJBiJcsA7/P4cc9GJ2EHnNthckACccUhkQcjUGCik2tjGlbpvpnhoTzmCTJpKKqmtQtUjfVWM+y0PkbZ1B+fwno7oLyY="
  bucket: sh.diogocardoso.me
  # Prevent Travis from deleting the build artifacts
  skip_cleanup: true
  region: eu-west-2
  # Deploy a single folder and not the entire project
  local_dir: build
after_deploy:
  - AWS_ACCESS_KEY_ID={$AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY={$AWS_SECRET_ACCESS_KEY} aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths /*
env:
  global:
    # Port
    - secure: "hLY6d7EpQC165jedLBzaZnNli8xQya3HmPmnpNuCMiei9WmT4/XIlUAsPfGZQVBGTQBIOlXKkvQAX+ldEdnWYErBimVjuT4nscqrBaPn6oeHHpDo2DBf/kvF5Fw1m8GToTAPcIoCAubvCrAlC9QN8e8V/z/WsThOVLYjMgADmBncOZlv7/KrRsuiglgK7QZyek5ywkFPR4VDIwLgt8nIefNv+bnu07SrNeUX7dTWGbnI3z045g6tL9AfU37zFUjR4iHMe1vdOI8igiA/RMA8NWq1+Av2tz9JOUHqTnNM52rIGR3xHIBRiRq9sZQw37YfV6bevq34lQLNg+En+ER7fydxvUng36BEVGXcYaAKfOdRjotvALF8TbU4cpqMSH2EjFV/DRtZWjtSZbYnss6chQW9wjsyIlCTQxOwJNeDEMZwHdepDalPDG+b1JXO8duS8Zb+0p1si7V6HdyjbYbZ0OyIF/JsN21K4oPXRU//xP6KCHaUQzWEBHJ4EPKEJdYL463apsUwxsT7fv9+Tpc4xFSCvicI1KWUjTXvWNhuMS6Zel7HfwsowwqeMi1/jiDmZij7dJDTXiibx3Im8C9ktWiaZh5Mu+fEOhoI5951yQnRgVUOCZiGpv8xjmjrMIt8tPTrKm6YAUyoS8nV24w1D8JB4XeF+MI3a0+NEQ0VBCU="
    # Mongo URI
    - secure: "IGDLrHaKjurOv2L4oLiaTljD6MHAO83qTftUqup748jKiKsvg2zFd7Hnwcd66yebCkOrOvf6hTnzzl9meCm4UhnThZGGyglSL+43fpvt7EoOmfVKR8ZWReB1h0spros3FnsP0Yad72dKkyTYHRVHWUZZCtVOmUU6i6rsWrjM8bIs6vvivl6ItrfP202okLPRoBhON71S+fIFkMSdI7LZ/FrwtnttQxK/C1hobCJsE32cGW/PnL7ZqLt5ROGZcq5cFkhn7x3Ygd+DAOnVcyoT3McCaugNl3mEG6+ozP1n9ByXRNt7vSgGFTyN8W8Do8r/tv9Jca4yl+djQTQzY2zTzsd4hjlnNdz6L6Z5GO6QNinkCGYkb0ZkNnCGaJf7U3B5gtcTI2ceIRedlWAToQBrV+F9nu3POILoTzqbZdxEoWysvfhuql5jSsrdue+zIVQ5QrFgMlNNNpLSN7/XcLSNQHKCFOA8GF16Y1G42cuBFk1iYUsErcec/RlyiXZVrteHAD2hKhxsh+LiDx00TT/O8/CWIevJAKhpn/ZH6tFOUDnmOsiI+K5V8tQT0tnKb+jI2Jsf+rNTz/c7FxwqYSMa+afOUr1bAv9Jjre0oiPYaloSHqcbco6RffK1uWVz3YHrKx55HzBxj9AucoKzrelJhv9af7bKjIGPZyUvoXdP4tw="
    # Mongo URI test
    - secure: "GL6Oq22PuElpsutHpHuWzYBLachMEWaNv0Hg0uZnocI8LAMmzmBbJUmgG8AcMMaRVJRr+9INz3yy7AjgZSyYkj0dYLagY5Y0iW3GZoXPn8SME++hzMEQKlTeYDktVGdVGZyq6clOLaIUbd5XU+dMz4efiZoXm6K9KvhCGCB0X9+pV4Up9pHkkn2HE6Xo2QIvCptPePRo9bem4/hJo+TodDPalbtb7Quez55sjGes1yLSMGgrctNuq7VvG7yvhb54Dx1o7+bwnI+Gm5lMvzNVQ9gKzcsy3pCzYgIsZjLT6dNFj68JQ5PTM71Psm7xR1tzFiWnEtKP1y6QQ1vzlTb/zfIcZEf96EJclBVtVjzBr1v3+Pa2rsTGgOvKJN0dB7Q5wJu32MkS86CTuUeoVoJyqAp3L378LEcdtpQhTurocPXyexkNL/aUunk+imUK+mpo2w0pqP0ugLPadkui5raG9mW+3v7FXsN4EH4NqIVISL0g8OUsOHDCw2KE3z3oQiwoQ2bXeOOjVWMxrs8BbK9VxNz5SaHT9FT3pOeBoyxt4w2VZfWQnke4ejWDfsh+U7Lt+d52yfmV8Mv/c6kRc/D13/UJ9vtpx4K4SrRqB7aJEw6ryNShOoZRyB7K993l9nm3/6dCv99O2AX13Nvph7q8Vr3nO2EDadfr2QjHa7CSq58="
    # Cloudfront Distribution ID
    - secure: "lc0aKGvW5e8XXYbS3niasewq/NIXzPZsBGeHmy5Q+QQXeLiIeJ8SwPGFjsAOFW7JgXlQeyzcDYlI99oF6Det4Gg9WjrFjR7oj9qsnAlhZBOXr86xgNLxEvPGbJNkdOZDhK2o+oevoMqv50ZcFxor9ftY90GqWS8OniXgMsQdfebXNZsPAQL5079Z38mmXTEmf1WzQ/iNCJoDOZyfByZv1vWWVQuXQNJuP3fYdgruM3zIcF6ZUWVZYsBmzbMCdIxkLkvSlaN0nHo1+FAb4RUqLmxBUkoe9l9GzIAvXhVqq36/S5e3CAbYSL2cNX5/OGcUmfznYKuZjJxgYIzcX2PrlzkxHoBIaM48HjpMX92VBOb+0fc128bvgmoVNDsSP5LRiBn4C0D/CMQ8ZtI3+qWdUkxPmWYqSJs5JE1V4tX/glpWNdfyOe1rb6OrjfMpR6NcGZawZ4RjU5/NDwgtIRq0KobTkfKHszPMRwR2xL+ARjDbJPnRPwBnpPKNKnrDTCV7GIEG7YGIWSYTtXX4LePYbU4Yn8XOnO1SyRreyEk3mXl/4hvZaaGDe8Kgdyv8+NVf8h4OOwxP+A3qQFpnwVvDwuxLzudE7x8PCrYsqcOU520KGQY86ard7R+zqWMFKlJNwEgVf7qQzFSR/bcx47hLn0h7V5fZq4P6IB/o1ZYEPNc="
    # AWS Access Key ID
    - secure: "EF5SQCjg1IrqwlPZ3+nyUwgre8ps2Yo8bLmcsi5L1jvfIyyeeWrXAom7uM9UeZsOy7MAgmCattUL31CqrV0pS+HWARiOpjuxhXZ9JD8ctbB7cF3CdF+9f1VMnKpBWEcsUGCH65OD9QHMmlym5nM3J1+JHtwL/a/R0Qw1zxtmz6fxbJ7G5qN065rpPKAr+pHYX9z4INaZ1TMk1i93xo529FJUCAYGx9iBRt3DNZ00LFdmn5BL7rxYx5WJvsJkIyfS6jsdAf6ZYnQgaiI57sVFyUWlorPrFVKOvw5mkDv/p67VmZTHNkcAQib4Iwj3JTXf1tM9rgQsdb1fqkKysjmwInaXINafvK6EBEJB0oAWGfAYP8Zu8nLClNec8j+PaSh8Czi8Jq1XGdJRTSAUiF0PByPsXISl4p2L3qQ1okb8FUMxsfepaaUkCsq5pL5rtg67Uf3G7Spb66A41L4acQWQ8rsKjPBmA+kul3q5smMHbc1DG3l2LZqaHrc2wiqMXaBxh8BsBC/n7Nt/QPr4K3Ni5rcLJXyfXffIvK16Zklw28HbrdXcJ/UDb2/KXesfv3fl0s3YA8XkatkcTyzknWdJ6mgjDOW9rdlAJXpAyq+trHxh9/0aokUJ+l0XyuYnzXBaDcG4Z6msV/xU2ou7S9RqfDUrq5KffF8QT4S5vvAJ1lE="
    # AWS Secret Access Key
    - secure: "aZx9tZz1QLNhiBf30rECzUCfeooTjUqBwecvkuattr18Ps4CY4IqZhqNS8v3GMn0mG1m5H7bYq86MsUqPFK/cBnbgF6VwBIrgUjUClcgTwfhDGJWcycCRRQIzxu8iqhPQeqwl+ccANILdwaeGgrLFd+X98iOIYxBPloMO112FBr/hiQgnOXIyaK6w4ZW1i0BE50umuo+HoDzqhXraq6sE7wrwSGbOhJpyRmK+73lniD9UOKhxCHB90Nl3+IGzAsG6NrFD0pHEsBtosdgAJ0uOjJgdfhYv649WNrczBMU5vnv32h7ZSlBpqk0mKUGPT8JWoFCnhItBcihFP19d49rOk/iG6M56YwWlnd9jnmhBL8ZmjSMJE4NcWZcsO+BX3C0vJH4pxplydYFDxpYG5S0Az6D1Q4+s8axg/mYwYwqpa+K/2Sjs/q+VoS0P+ico++szAIgxD9bXaQERydyDAvEFYFhAWOgn+FyLEdKsv7yueRyn2oG99+/6fLN9nkrFD/8hn67hTcCJFLcjX/1FeiMLgNAUvMzoa4dgXx2rMpFsI0hS5o8Bj4OIZf8o0Ns4w9c+pRZCrbV50Jrc6mwqxniQAThDMmKe37O0h2Zknr2yxUVDZmn1hHAHfM/ysCo2LTlMthTOmacQmy3GYMY0IeIs9YkI61A0vIdHwufmFf30F0="
